export const STORY_FETCH_REQUEST = 'STORY_FETCH_REQUEST';
export const STORY_FETCH_SUCCESS = 'STORY_FETCH_SUCCESS';
export const STORY_FETCH_FAILURE = 'STORY_FETCH_FAILURE';
export const STORY_LAZY_REQUEST = 'STORY_LAZY_REQUEST';
export const STORY_LAZY_SUCCESS = 'STORY_LAZY_SUCCESS';
export const STORY_LAZY_FAILURE = 'STORY_LAZY_FAILURE';
