// export const COMMENT_FETCH_REQUEST = 'COMMENT_FETCH_REQUEST';
// export const COMMENT_FETCH_SUCCESS = 'COMMENT_FETCH_SUCCESS';
// export const COMMENT_FETCH_FAILURE = 'COMMENT_FETCH_FAILURE';
export const COMMENT_LAZY_REQUEST = 'COMMENT_LAZY_REQUEST';
export const COMMENT_LAZY_SUCCESS = 'COMMENT_LAZY_SUCCESS';
export const COMMENT_LAZY_FAILURE = 'COMMENT_LAZY_FAILURE';
